site_name: StudioComponents
site_url: https://sircfenner.github.io/StudioComponents/

repo_name: sircfenner/StudioComponents
repo_url: https://github.com/sircfenner/StudioComponents

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: teal

extra_css:
  - extra.css

nav:
  - Home: index.md
  - Guide:
    - Installation: guide/installation.md
    - Usage: guide/usage.md
  - Components:
    - Background: components/background.md
    - Button: components/button.md
    - Checkbox: components/checkbox.md
    - Label: components/label.md
    - MainButton: components/mainbutton.md
    - ScrollFrame: components/scrollframe.md
    - Slider: components/slider.md
    - TextInput: components/textinput.md
    - VerticalCollapsibleSection: components/verticalcollapsiblesection.md
    - VerticalExpandingList: components/verticalexpandinglist.md
    - Widget: components/widget.md

markdown_extensions:
  - admonition